version: "2"

run:
  timeout: 3m

linters:
  default: standard
  enable:
    - errorlint
    - gocritic
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam

formatters:
  enable:
    - gofumpt
    - goimports
